# Generated by Django 4.2.6 on 2023-10-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="userActivity",
            field=models.TextField(default="abc"),
            preserve_default=False,
        ),
    ]
