# Generated by Django 4.2.6 on 2023-11-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_activity_useractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="userType",
            field=models.IntegerField(
                choices=[(0, "Type A: International"), (1, "Type E: Egyptian")],
                default=0,
            ),
        ),
    ]
