# Generated by Django 4.2.6 on 2023-11-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_user_grade"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="department",),
        migrations.RemoveField(model_name="user", name="expert",),
        migrations.RemoveField(model_name="user", name="hrCode",),
        migrations.RemoveField(model_name="user", name="isMobilized",),
        migrations.RemoveField(model_name="user", name="natGroup",),
        migrations.RemoveField(model_name="user", name="position",),
        migrations.RemoveField(model_name="user", name="workingLocation",),
    ]
