# Generated by Django 4.2.6 on 2023-11-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_rename_grade_user_usergrade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="userGrade", new_name="grade",
        ),
    ]
