# Generated by Django 4.2.6 on 2023-11-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_user_department_user_expert_user_ismobilized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="natGroup",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Vice Chairman"),
                    (1, "Follow Up Department"),
                    (2, "Technical Department"),
                    (3, "Civil Work Department"),
                    (4, "Power Supply Department"),
                    (5, "Rolling Stock & Mechanical Department"),
                ],
                null=True,
            ),
        ),
    ]
