# Generated by Django 4.2.6 on 2023-11-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organizationCode",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
