# Generated by Django 4.2.6 on 2023-11-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_user_organizationcode"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="isMobilized",),
        migrations.AddField(
            model_name="user",
            name="mobilization",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
