# Generated by Django 4.2.6 on 2023-11-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_remove_user_ismobilized_user_mobilization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "OCG"), (1, "NK"), (2, "EHAF"), (3, "ACE")],
                null=True,
            ),
        ),
    ]
