# Generated by Django 4.2.6 on 2023-11-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_user_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="activityType",
            field=models.IntegerField(
                blank=True, choices=[(0, "H"), (1, "C"), (2, "X"), (3, "J")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="userActivity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "A1"),
                    (1, "A2"),
                    (2, "A3"),
                    (3, "B1"),
                    (4, "B2"),
                    (5, "B3"),
                    (6, "B4"),
                    (7, "B5"),
                ],
                null=True,
            ),
        ),
    ]
