# Generated by Django 4.2.6 on 2023-11-09 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_alter_activity_activitytype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activityType",
            field=models.IntegerField(
                choices=[(0, "H"), (1, "C"), (2, "X"), (3, "J")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
