# Generated by Django 4.2.6 on 2023-11-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_company_alter_user_company"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="company",),
        migrations.DeleteModel(name="Company",),
    ]
