# Generated by Django 4.2.6 on 2023-11-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_company_user_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isAccepted",
            field=models.BooleanField(default=False),
        ),
    ]
