# Generated by Django 4.2.6 on 2023-11-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_user_isaccepted"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="isAccepted",),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "OCG"), (1, "NK"), (2, "EHAF"), (3, "ACE")],
                null=True,
            ),
        ),
        migrations.DeleteModel(name="Company",),
    ]
