# Generated by Django 4.2.6 on 2023-11-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_remove_user_isaccepted_alter_user_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="needsPasswordReset",
            field=models.BooleanField(default=True),
        ),
    ]
