# Generated by Django 4.2.6 on 2023-11-12 21:37

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_user_needspasswordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityDate',
            field=models.DateField(default=datetime.date(2023, 11, 12)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
