# Generated by Django 4.2.6 on 2023-11-14 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_activity_activitydate_alter_activity_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityDate',
            field=models.DateField(default=datetime.date(2023, 11, 14)),
        ),
        migrations.AlterField(
            model_name='user',
            name='natGroup',
            field=models.IntegerField(blank=True, choices=[(0, 'VCH'), (1, 'FUD'), (2, 'TD'), (3, 'CWD'), (4, 'PSD'), (5, 'RSMD')], null=True),
        ),
    ]
