# Generated by Django 4.2.6 on 2023-12-07 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0037_alter_activity_activitydate_alter_activity_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendarType",
            field=models.IntegerField(
                blank=True,
                choices=[("EXP_CAL", "Expert Calendar"), ("LOC_CAL", "Local Calendar")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activityDate",
            field=models.DateField(default=datetime.date(2023, 12, 7)),
        ),
    ]
