# Generated by Django 4.2.6 on 2023-12-17 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0038_user_calendartype_alter_activity_activitydate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activityDate",
            field=models.DateField(default=datetime.date(2023, 12, 17)),
        ),
        migrations.AlterField(
            model_name="user",
            name="calendarType",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Expert Calendar"), (1, "Local Calendar")],
                null=True,
            ),
        ),
    ]
