# Generated by Django 4.2.6 on 2023-12-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0039_alter_activity_activitydate_alter_user_calendartype"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="user_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
