# Generated by Django 4.2.6 on 2024-01-07 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0041_alter_activity_activitydate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activityDate",
            field=models.DateField(default=datetime.date(2024, 1, 7)),
        ),
    ]
