# Generated by Django 4.2.6 on 2024-02-02 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0043_activityfile_alter_activity_activitydate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activityDate",
            field=models.DateField(default=datetime.date(2024, 2, 2)),
        ),
    ]
