# Generated by Django 4.2.6 on 2024-02-10 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0045_alter_activity_activitydate_alter_activityfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activityDate",
            field=models.DateField(default=datetime.date(2024, 2, 10)),
        ),
    ]
