# Generated by Django 4.2.6 on 2024-02-14 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0046_alter_activity_activitydate"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityfile",
            name="file_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activityDate",
            field=models.DateField(default=datetime.date(2024, 2, 14)),
        ),
    ]
