# Generated by Django 4.2.6 on 2024-02-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0048_hrhistory_alter_activity_activitydate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrhistory",
            name="hrCode",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
