# Generated by Django 4.2.6 on 2024-04-03 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0049_alter_hrhistory_hrcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityFile",
        ),
        migrations.AlterField(
            model_name="activity",
            name="activityDate",
            field=models.DateField(default=datetime.date(2024, 4, 3)),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "OCG"), (1, "NK"), (2, "EHAF"), (3, "ACE"), (4, "TD")],
                null=True,
            ),
        ),
    ]
